### ISSUE TITLE
Footer Fine Print Mismatch

### ISSUE THREAD

**Issue by enathu** [akuru/akurucon.com#6]
The content of the footer fine print mismatching with all three languages. Please have a look 

> සංවිධානය: අකුරු සාමූහිකය සහ මූනියැක් විසින්, නෙදර්ලන්ත රාජධානියේ තානාපති කාර්යාලයේ සහ AOD එකමුතුවෙන්, ශ්‍රී ලංකා රාජකීය ආසියාතික සංගමයේ සහයෝගයෙන්,
> 
> அகுரு குழுமம், மூனியக், AOD அத்தோடு நெதர்லாந்து தூதரகலாயத்துடன் இணைந்தும் தேசிய சுவடிகள் கூட்டுத்தாபனத்தின் ஒத்துழைப்புடன் ஏற்பாடு செய்யப்பட்டுள்ளது.
> 
> Organised by Akuru Collective and Mooniak in collaboration with AOD and with the support from The Embassy of The Kingdom of the Netherlands in Sri Lanka.

**Comment by pathumego** [comment]
@enathu Can you give me a updated Tamil text.

**Comment by pathumego** [comment]
Sinhala fix
`සංවිධානය: අකුරු සාමූහිකය සහ මූනියැක් විසින්,  AOD එකමුතුවෙන් සහ නෙදර්ලන්ත රාජධානියේ තානාපති කාර්යාලයේ සහයෝගයෙන්`

**Comment by enathu** [comment]
Tamil version!

ஏற்பாடு: அகுரு குழுமம் மற்றும் மூனியக் ஆகியவற்றோடு AOD இன் கூட்டிணைவுடனும் நெதர்லாந்து தூதரக அலுவலகத்தின் ஒத்துழைப்புடனும்..
